dist: xenial

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

install:
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpcs --standard=PhpMyAdmin -vv | grep -oF "Processing ruleset $(pwd)/PhpMyAdmin/ruleset.xml"
